export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';
export const SET_COMMON_REDUCER = 'SET_COMMON_REDUCER';
export const UPDATE_VALUES_FROM_SERVER = 'UPDATE_VALUES_FROM_SERVER';
export const GET_SUBSCRIPTIONS_DETAILS = 'GET_SUBSCRIPTIONS_DETAILS';
export const SET_GEO_FENCE = 'SET_GEO_FENCE';
